name: meta-trader

startup_window: shell

windows:
  - editor: nvim .
  - shell:
  - claude:
      - alias run="tmux rename-window -t\${TMUX_PANE} 'claude'; clear; claude --dangerously-skip-permissions; tmux rename-window -t\${TMUX_PANE} '🔴 claude'"
      - run
  - git: tig
